/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/pranganmajumder/crd/pkg/apis/demo.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUserInfos implements UserInfoInterface
type FakeUserInfos struct {
	Fake *FakeDemoV1alpha1
	ns   string
}

var userinfosResource = schema.GroupVersionResource{Group: "demo.com", Version: "v1alpha1", Resource: "userinfos"}

var userinfosKind = schema.GroupVersionKind{Group: "demo.com", Version: "v1alpha1", Kind: "UserInfo"}

// Get takes name of the userInfo, and returns the corresponding userInfo object, and an error if there is any.
func (c *FakeUserInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UserInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(userinfosResource, c.ns, name), &v1alpha1.UserInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UserInfo), err
}

// List takes label and field selectors, and returns the list of UserInfos that match those selectors.
func (c *FakeUserInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UserInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(userinfosResource, userinfosKind, c.ns, opts), &v1alpha1.UserInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UserInfoList{ListMeta: obj.(*v1alpha1.UserInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.UserInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested userInfos.
func (c *FakeUserInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(userinfosResource, c.ns, opts))

}

// Create takes the representation of a userInfo and creates it.  Returns the server's representation of the userInfo, and an error, if there is any.
func (c *FakeUserInfos) Create(ctx context.Context, userInfo *v1alpha1.UserInfo, opts v1.CreateOptions) (result *v1alpha1.UserInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(userinfosResource, c.ns, userInfo), &v1alpha1.UserInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UserInfo), err
}

// Update takes the representation of a userInfo and updates it. Returns the server's representation of the userInfo, and an error, if there is any.
func (c *FakeUserInfos) Update(ctx context.Context, userInfo *v1alpha1.UserInfo, opts v1.UpdateOptions) (result *v1alpha1.UserInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(userinfosResource, c.ns, userInfo), &v1alpha1.UserInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UserInfo), err
}

// Delete takes name of the userInfo and deletes it. Returns an error if one occurs.
func (c *FakeUserInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(userinfosResource, c.ns, name), &v1alpha1.UserInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUserInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(userinfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UserInfoList{})
	return err
}

// Patch applies the patch and returns the patched userInfo.
func (c *FakeUserInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UserInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(userinfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.UserInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UserInfo), err
}
