/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/pranganmajumder/crd/pkg/apis/demo.com/v1alpha1"
	scheme "github.com/pranganmajumder/crd/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UserInfosGetter has a method to return a UserInfoInterface.
// A group's client should implement this interface.
type UserInfosGetter interface {
	UserInfos(namespace string) UserInfoInterface
}

// UserInfoInterface has methods to work with UserInfo resources.
type UserInfoInterface interface {
	Create(ctx context.Context, userInfo *v1alpha1.UserInfo, opts v1.CreateOptions) (*v1alpha1.UserInfo, error)
	Update(ctx context.Context, userInfo *v1alpha1.UserInfo, opts v1.UpdateOptions) (*v1alpha1.UserInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.UserInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UserInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UserInfo, err error)
	UserInfoExpansion
}

// userInfos implements UserInfoInterface
type userInfos struct {
	client rest.Interface
	ns     string
}

// newUserInfos returns a UserInfos
func newUserInfos(c *DemoV1alpha1Client, namespace string) *userInfos {
	return &userInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the userInfo, and returns the corresponding userInfo object, and an error if there is any.
func (c *userInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UserInfo, err error) {
	result = &v1alpha1.UserInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("userinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UserInfos that match those selectors.
func (c *userInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UserInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UserInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("userinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested userInfos.
func (c *userInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("userinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a userInfo and creates it.  Returns the server's representation of the userInfo, and an error, if there is any.
func (c *userInfos) Create(ctx context.Context, userInfo *v1alpha1.UserInfo, opts v1.CreateOptions) (result *v1alpha1.UserInfo, err error) {
	result = &v1alpha1.UserInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("userinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(userInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a userInfo and updates it. Returns the server's representation of the userInfo, and an error, if there is any.
func (c *userInfos) Update(ctx context.Context, userInfo *v1alpha1.UserInfo, opts v1.UpdateOptions) (result *v1alpha1.UserInfo, err error) {
	result = &v1alpha1.UserInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("userinfos").
		Name(userInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(userInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the userInfo and deletes it. Returns an error if one occurs.
func (c *userInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("userinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *userInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("userinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched userInfo.
func (c *userInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UserInfo, err error) {
	result = &v1alpha1.UserInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("userinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
