/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/pranganmajumder/crd/pkg/apis/appscode.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApployments implements ApploymentInterface
type FakeApployments struct {
	Fake *FakeAppscodeV1alpha1
	ns   string
}

var apploymentsResource = schema.GroupVersionResource{Group: "appscode.com", Version: "v1alpha1", Resource: "apployments"}

var apploymentsKind = schema.GroupVersionKind{Group: "appscode.com", Version: "v1alpha1", Kind: "Apployment"}

// Get takes name of the apployment, and returns the corresponding apployment object, and an error if there is any.
func (c *FakeApployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Apployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apploymentsResource, c.ns, name), &v1alpha1.Apployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apployment), err
}

// List takes label and field selectors, and returns the list of Apployments that match those selectors.
func (c *FakeApployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apploymentsResource, apploymentsKind, c.ns, opts), &v1alpha1.ApploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ApploymentList{ListMeta: obj.(*v1alpha1.ApploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.ApploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apployments.
func (c *FakeApployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apploymentsResource, c.ns, opts))

}

// Create takes the representation of a apployment and creates it.  Returns the server's representation of the apployment, and an error, if there is any.
func (c *FakeApployments) Create(ctx context.Context, apployment *v1alpha1.Apployment, opts v1.CreateOptions) (result *v1alpha1.Apployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apploymentsResource, c.ns, apployment), &v1alpha1.Apployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apployment), err
}

// Update takes the representation of a apployment and updates it. Returns the server's representation of the apployment, and an error, if there is any.
func (c *FakeApployments) Update(ctx context.Context, apployment *v1alpha1.Apployment, opts v1.UpdateOptions) (result *v1alpha1.Apployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apploymentsResource, c.ns, apployment), &v1alpha1.Apployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apployment), err
}

// Delete takes name of the apployment and deletes it. Returns an error if one occurs.
func (c *FakeApployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apploymentsResource, c.ns, name), &v1alpha1.Apployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ApploymentList{})
	return err
}

// Patch applies the patch and returns the patched apployment.
func (c *FakeApployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Apployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apploymentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Apployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apployment), err
}
