apiVersion: appscode.com/v1alpha1
kind: Apployment
metadata:
  name: apiserver-apployment

spec:
  apployment_name: testing
  replicas: 2
  image: pranganmajumder/go-basic-restapi:1.0.4
  service_type: NodePort
  node_port: 31002
  container_port: 8080
  label:
    test: aclabel

