/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	democomv1alpha1 "github.com/pranganmajumder/crd/pkg/apis/demo.com/v1alpha1"
	versioned "github.com/pranganmajumder/crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/pranganmajumder/crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/pranganmajumder/crd/pkg/client/listers/demo.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UserInfoInformer provides access to a shared informer and lister for
// UserInfos.
type UserInfoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.UserInfoLister
}

type userInfoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewUserInfoInformer constructs a new informer for UserInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUserInfoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUserInfoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredUserInfoInformer constructs a new informer for UserInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUserInfoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().UserInfos(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().UserInfos(namespace).Watch(context.TODO(), options)
			},
		},
		&democomv1alpha1.UserInfo{},
		resyncPeriod,
		indexers,
	)
}

func (f *userInfoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUserInfoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *userInfoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&democomv1alpha1.UserInfo{}, f.defaultInformer)
}

func (f *userInfoInformer) Lister() v1alpha1.UserInfoLister {
	return v1alpha1.NewUserInfoLister(f.Informer().GetIndexer())
}
